### ISSUE TITLE
Dht service 

### ISSUE THREAD

**Issue by Nadim-os** [RaresAil/homebridge-gree-ac#11]
Hello i am using this plugin everything is going well but the ambient temps
I recognize that i need a dht22 sensor  to make the service works 
The question is if i need a dht sensor for each ac or one sensor will do the job for all my ac
Knowing that i have a rpi 4

**Comment by RaresAil** [comment]
Hey, a single sensor is enough, because there will be only one service for the sensor and all ACs will get the data from there
