### ISSUE TITLE
DHT Service for 2 heatpump ?

### ISSUE THREAD

**Issue by BenPicard** [RaresAil/homebridge-gree-ac#14]
Hi,

I have 1 heatpump by floor (2 totals). I was wondering if there is a way to have 2 DHT Service with different value? The temperature and the humidity will not be the same on each floor.

Regards,

**Comment by RaresAil** [comment]
Hey, for the AC no, but, i have another plugin which is just the DHT sensor and you can use the other one for the secondary sensor

https://github.com/RaresAil/homebridge-temperature-sensor-dht
