### ISSUE TITLE
External temperature service, per A/C unit

### ISSUE THREAD

**Issue by nwrightau** [RaresAil/homebridge-gree-ac#16]
Hi, thanks for your plugin it works quite well. 

I'm experimenting with the DHT Service but i'd rather pull data from existing homebridge plugins that already have sensors, problem is I have multiple A/Cs in different rooms but can only specify one temperature sensor for both units.

Would you consider allowing a service to be specified for each unit?

Cheers

**Comment by RaresAil** [comment]
Hey, i have a separate plugin just for temperature sensor, you can use that one
