### ISSUE TITLE
Able to add in Homekit, but unable to control ACs.

### ISSUE THREAD

**Issue by omeroman0** [RaresAil/homebridge-gree-ac#17]
**Describe Your Problem:**
The buttons on the Home app are responsive, meaning you can interact with them, but can neither control the units or reflect the current status of the AC units. I removed the gree bridge from homekit, and re-added it. All three units were identified readily but the same thing happened -- even if the UI changes on my phone, it doesn't control anything and does not update when the AC is controlled manually. 

Logs don't seem to register anything wrong. I have used this plugin for about 4-5 months, and it has worked before. So it's a surprise it just stopped working. Is this because of a change in architecture recently in iOS? Currently on iOS 16.2

**Logs:**

```
[12/22/2022, 10:25:58 PM] [Gree ACs] Loading accessory from cache: AC1
[12/22/2022, 10:25:58 PM] [Gree ACs] Loading accessory from cache: AC2
[12/22/2022, 10:25:58 PM] [Gree ACs] Loading accessory from cache: AC3
```

**Plugin Config:**

```json
        {
            "name": "Gree ACs",
            "broadcastAddress": "Local IP",
            "threeSpeedUnit": true,
            "coolingMinTemp": 16,
            "coolingMaxTemp": 30,
            "heatingMinTemp": 16,
            "heatingMaxTemp": 30,
            "defaultCurrentTemp": 30,
            "dhtService": "",
            "_bridge": {
                "username": "MAC Addr",
                "port": 53127
            },
            "platform": "GreeACImplementationPlugin"
        },
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v1.2.1
* **Homebridge Version**: 1.6.0
* **Node.js Version**: v18.12.1
* **NPM Version**: 8.19.2
* **Operating System**: Docker | Ubuntu Focal Fossa (20.04.5 LTS)

**Comment by RaresAil** [comment]
Hey, did the issue occurred after the ios update?

**Comment by RaresAil** [comment]
Try update all the devices, like homepod or the hub in the house, homebridge, and if that still not working, clean the cache on hombridge and setup again the plugin
