### ISSUE TITLE
How to add more than one AC ?

### ISSUE THREAD

**Issue by arkhi124** [RaresAil/homebridge-gree-ac#2]
How to add more than one AC ?

**Comment by RaresAil** [comment]
Hello, sorry for the late response, this should be automatically, if both ACs are connected to the same wifi, the platform plugin should detect them both, I don't have 2 different AC to can test this, but make sure the broadcast address is the correct one.

**Comment by arkhi124** [comment]
thanks for your reply. i have 2 ac, but they have different ip adresses 
i thought, i need to set two ip adresses (

**Comment by arkhi124** [comment]
i set wrong broadcast adress, all working correct, thank you!
