### ISSUE TITLE
Wrong temperature reading

### ISSUE THREAD

**Issue by kmedakovic** [RaresAil/homebridge-gree-ac#3]
My AC shows current temperature as 45*C. Actual temperature is 22*C. What can be the issue?

**Comment by chunheisiu** [comment]
Did you set the URL for `dhtService`?  I don't have a Raspberry Pi so I am getting 45C as well.

**Comment by kmedakovic** [comment]
I don’t know how to set the URL for dhtService

**Comment by chunheisiu** [comment]
> I don’t know how to set the URL for dhtService

I believe there is a sample in the README:

```json
{
  "platforms": [
    {
     "platform": "GreeACImplementationPlugin",
      ...,
      "dhtService": "http://localhost:55555"
    }
  ]
}
```

**Comment by chunheisiu** [comment]
@kmedakovic I have moved on to using this plugin. Hope it works for you as well.
https://github.com/kongkx/homebridge-gree-air-conditioner

**Comment by kmedakovic** [comment]
@chunheisiu I have moved on as well and the temperature reading is correct now!

**Comment by RaresAil** [comment]
For the dhtService to work, you need to connect a DHT sensor to the PI and run a service which reads that value and stream it over http.

**Comment by RaresAil** [comment]
There is a script on how to setup the dht service for that: https://github.com/RaresAil/homebridge-gree-ac#dht-service
